// flow-typed signature: b2370012006c547749174f7b6fb62ce8
// flow-typed version: <<STUB>>/graphql-compiler_v1.7.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-compiler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-compiler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-compiler/graphql-compiler' {
  declare module.exports: any;
}

declare module 'graphql-compiler/graphql-compiler.min' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/areEqualOSS' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/ASTCache' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/ASTConvert' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/CodegenDirectory' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/CodegenRunner' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/CodegenTypes' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/CodegenWatcher' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/DefaultHandleKey' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/DotGraphQLParser' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/filterContextForNode' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/FilterDirectivesTransform' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/FlattenTransform' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/getIdentifierForArgumentValue' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/getIdentifierForSelection' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/getLiteralArgumentValues' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/GraphQLCompilerContext' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/GraphQLCompilerProfiler' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/GraphQLCompilerPublic' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/GraphQLCompilerUserError' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/GraphQLConsoleReporter' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/GraphQLIR' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/GraphQLIRPrinter' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/GraphQLIRTransformer' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/GraphQLIRTransforms' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/GraphQLIRVisitor' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/GraphQLMultiReporter' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/GraphQLParser' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/GraphQLReporter' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/GraphQLSchemaUtils' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/GraphQLValidator' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/GraphQLWatchmanClient' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/InlineFragmentsTransform' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/isEquivalentType' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/nullthrowsOSS' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/SkipClientFieldTransform' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/SkipRedundantNodesTransform' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/SkipUnreachableNodeTransform' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/SourceControl' {
  declare module.exports: any;
}

declare module 'graphql-compiler/lib/StripUnusedVariablesTransform' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-compiler/graphql-compiler.js' {
  declare module.exports: $Exports<'graphql-compiler/graphql-compiler'>;
}
declare module 'graphql-compiler/graphql-compiler.min.js' {
  declare module.exports: $Exports<'graphql-compiler/graphql-compiler.min'>;
}
declare module 'graphql-compiler/index' {
  declare module.exports: $Exports<'graphql-compiler'>;
}
declare module 'graphql-compiler/index.js' {
  declare module.exports: $Exports<'graphql-compiler'>;
}
declare module 'graphql-compiler/lib/areEqualOSS.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/areEqualOSS'>;
}
declare module 'graphql-compiler/lib/ASTCache.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/ASTCache'>;
}
declare module 'graphql-compiler/lib/ASTConvert.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/ASTConvert'>;
}
declare module 'graphql-compiler/lib/CodegenDirectory.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/CodegenDirectory'>;
}
declare module 'graphql-compiler/lib/CodegenRunner.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/CodegenRunner'>;
}
declare module 'graphql-compiler/lib/CodegenTypes.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/CodegenTypes'>;
}
declare module 'graphql-compiler/lib/CodegenWatcher.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/CodegenWatcher'>;
}
declare module 'graphql-compiler/lib/DefaultHandleKey.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/DefaultHandleKey'>;
}
declare module 'graphql-compiler/lib/DotGraphQLParser.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/DotGraphQLParser'>;
}
declare module 'graphql-compiler/lib/filterContextForNode.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/filterContextForNode'>;
}
declare module 'graphql-compiler/lib/FilterDirectivesTransform.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/FilterDirectivesTransform'>;
}
declare module 'graphql-compiler/lib/FlattenTransform.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/FlattenTransform'>;
}
declare module 'graphql-compiler/lib/getIdentifierForArgumentValue.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/getIdentifierForArgumentValue'>;
}
declare module 'graphql-compiler/lib/getIdentifierForSelection.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/getIdentifierForSelection'>;
}
declare module 'graphql-compiler/lib/getLiteralArgumentValues.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/getLiteralArgumentValues'>;
}
declare module 'graphql-compiler/lib/GraphQLCompilerContext.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/GraphQLCompilerContext'>;
}
declare module 'graphql-compiler/lib/GraphQLCompilerProfiler.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/GraphQLCompilerProfiler'>;
}
declare module 'graphql-compiler/lib/GraphQLCompilerPublic.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/GraphQLCompilerPublic'>;
}
declare module 'graphql-compiler/lib/GraphQLCompilerUserError.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/GraphQLCompilerUserError'>;
}
declare module 'graphql-compiler/lib/GraphQLConsoleReporter.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/GraphQLConsoleReporter'>;
}
declare module 'graphql-compiler/lib/GraphQLIR.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/GraphQLIR'>;
}
declare module 'graphql-compiler/lib/GraphQLIRPrinter.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/GraphQLIRPrinter'>;
}
declare module 'graphql-compiler/lib/GraphQLIRTransformer.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/GraphQLIRTransformer'>;
}
declare module 'graphql-compiler/lib/GraphQLIRTransforms.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/GraphQLIRTransforms'>;
}
declare module 'graphql-compiler/lib/GraphQLIRVisitor.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/GraphQLIRVisitor'>;
}
declare module 'graphql-compiler/lib/GraphQLMultiReporter.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/GraphQLMultiReporter'>;
}
declare module 'graphql-compiler/lib/GraphQLParser.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/GraphQLParser'>;
}
declare module 'graphql-compiler/lib/GraphQLReporter.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/GraphQLReporter'>;
}
declare module 'graphql-compiler/lib/GraphQLSchemaUtils.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/GraphQLSchemaUtils'>;
}
declare module 'graphql-compiler/lib/GraphQLValidator.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/GraphQLValidator'>;
}
declare module 'graphql-compiler/lib/GraphQLWatchmanClient.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/GraphQLWatchmanClient'>;
}
declare module 'graphql-compiler/lib/InlineFragmentsTransform.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/InlineFragmentsTransform'>;
}
declare module 'graphql-compiler/lib/isEquivalentType.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/isEquivalentType'>;
}
declare module 'graphql-compiler/lib/nullthrowsOSS.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/nullthrowsOSS'>;
}
declare module 'graphql-compiler/lib/SkipClientFieldTransform.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/SkipClientFieldTransform'>;
}
declare module 'graphql-compiler/lib/SkipRedundantNodesTransform.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/SkipRedundantNodesTransform'>;
}
declare module 'graphql-compiler/lib/SkipUnreachableNodeTransform.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/SkipUnreachableNodeTransform'>;
}
declare module 'graphql-compiler/lib/SourceControl.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/SourceControl'>;
}
declare module 'graphql-compiler/lib/StripUnusedVariablesTransform.js' {
  declare module.exports: $Exports<'graphql-compiler/lib/StripUnusedVariablesTransform'>;
}
